#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'RUNNING GIT HOOKS'

echo 'Checking Validity Of Types'

pnpm type-check || (
    echo '⛔️ There is a TYPE ERROR on your code, please fix it and do commit again ⛔️';
    false;
)

echo '🎉 No Type Error found: committing this now.... ✨🚀🏄‍♂️🍻'

pnpm exec lint-staged