#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'RUNNING GIT HOOKS'

echo 'Checking Validity Of Types'

yarn type-check || (
    echo '⛔️ There is a TYPE ERROR on your code, please fix it and do commit again ⛔️';
    false;
)

echo 'No Type Error ✅'

echo 'Running linter'

# Check ESLint Standards
yarn lint ||
(
    echo '⛔️ There is an ESLINT ERROR on your code, please fix it and do commit again ⛔️';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged